### ISSUE TITLE
the file agi.mis is missing

### ISSUE THREAD

**Issue by williamyuanv0** [bupticybee/AlphaNLHoldem#1]
Hi! icybee, 
      The file _agi.mis_ in _train_league.py_ might be missing.

**Comment by williamyuanv0** [comment]
And could you please provide a Baidu web disk link of the released data ？

**Comment by bupticybee** [comment]
> Hi! icybee, The file _agi.mis_ in _train_league.py_ might be missing.

It's now fixed in 

https://github.com/bupticybee/AlphaNLHoldem/commit/ebd5a9c401146446324d86dd0373a768556f7996

**Comment by bupticybee** [comment]
> And could you please provide a Baidu web disk link of the released data ？

baidu netdisk url has been added in readme.

**Comment by bupticybee** [comment]
Closing, problem considered solved.
