### ISSUE TITLE
Training speed is slow and not utilizing all cores.

### ISSUE THREAD

**Issue by bluedevils23** [bupticybee/AlphaNLHoldem#10]
I don't know why my training speed is slower comparing to your screenshot.
CPU e5-2997v4 18cores and 200GB memory. 1 iter uses average 200 seconds. and seems only 1 core is used all the time. not sure   if there are some config error.
![training](https://github.com/user-attachments/assets/d7a029e2-4500-4cf7-a0aa-90980eb55f41)

**Comment by bupticybee** [comment]
I'm testing on 90 core machine, Not surprising.

**Comment by bupticybee** [comment]
You need to understand the whole system a little bit more, tuning throughput in RL is not an easy task, it has to be done according to machine specifics and task.

**Comment by bupticybee** [comment]
100 frame/s is extrame low from my point of view.

**Comment by bluedevils23** [comment]
Resolved by setting "num_workers" less than cpu cores. Now 1 iter only 10 secs.

**Comment by bluedevils23** [comment]
close

**Comment by bluedevils23** [comment]
closing
