### ISSUE TITLE
Issues in RLCard environment

### ISSUE THREAD

**Issue by daochenzha** [bupticybee/AlphaNLHoldem#2]
Thanks for the great work!

Would you mind sharing more details about the issues in the RLCard environment? We want to fix them.

**Comment by bupticybee** [comment]
> Thanks for the great work!
> 
> Would you mind sharing more details about the issues in the RLCard environment? We want to fix them.
 
Major problems:

1. you use 50bb pot, which is not standard 100bb setting 
2. bet sizes are wrong, if you want to fix them, check it with  https://www.slumbot.com/ make sure you use the same bet sizes in every branch of the game tree
3. after a bet-call/check-call in pre-flop, IP player act first in flop, in which case you got it all wrong.

I'm thinking if we could discuss further in some way , I'm interested in discussing some of your previous works (rlcard, douzero,etc) and possible future directions, and of course also, about nl-holdem.

I'm a researcher in bytedance AI lab, located in Shenzhen. Looking forward for further discussion.

**Comment by daochenzha** [comment]
@bupticybee Thank you for providing the information. @ruzhwei will follow up. Yes, I am happy to chat. My WeChat is zdcwhu

**Comment by bupticybee** [comment]
Closing
