### ISSUE TITLE
Issues with available releases of the Ray Library?

### ISSUE THREAD

**Issue by DigitalBluff** [bupticybee/AlphaNLHoldem#4]
Is there any way to make this work on any of the Ray releases that are available for install using pip? The furthest version that I can go back to is 0.8.6, but there seems to be a lot of unsupported code when I tried that version.

Is 0.8.3 a must? If so, are there any sources for it still available that I can compile for my machine?

Thanks in advance!

**Comment by bupticybee** [comment]
Yes, actually I'm planning to transfer the code to latest version. No, 0.8.3 is not a must, please specific your platform, linux? max? windows? I found ray's version number differs in those three platforms.

For now this project's training is only supported in linux, not windows and mac.

**Comment by DigitalBluff** [comment]
Ah ok, that makes a lot of sense. I'm trying to run the code on Windows, but i'm getting a lot of errors regarding modules not being found/available across the versions that I have tried (0.8.6, 1.1, 2.4) when trying to run the "play against ai" python script.

I'll give it a shot on a Linux machine when I get a chance after reading your comments. I'm quite surprised that the Ray versions differ so much across platforms?

Thanks!

**Comment by bupticybee** [comment]
> Ah ok, that makes a lot of sense. I'm trying to run the code on Windows, but i'm getting a lot of errors regarding modules not being found/available across the versions that I have tried (0.8.6, 1.1, 2.4) when trying to run the "play against ai" python script.
> 
> I'll give it a shot on a Linux machine when I get a chance after reading your comments. I'm quite surprised that the Ray versions differ so much across platforms?
> 
> Thanks!

Yes, the older version of ray is sowhat bad in some sense.

**Comment by bupticybee** [comment]
Closing because this issue is considered solved. Reopen if necessary.
